### ISSUE TITLE
Unwanted newlines being added

### ISSUE THREAD

**Issue by whaynes** [skiadas/ptx-formatter#39]
Each time the formatter runs on this sample document, more blank lines get added.   

I would expect that once a document has been formatted, the results would not change if it is formatted again.

```<chapter>
  <title>test formatting</title>
  <p>
    The Pythagorean Theorem states
    <me>r = \sqrt{{x^2}+{y^2}}</me>.
  </p>
  <p>
    <md>
      <mrow>(a+b)^2</mrow>
    </md>
    .  Now...
  </p>
</chapter>```

**Comment by skiadas** [comment]
Looks like the issue here might be block-rendered tags whose last child is a text node. For some reason they keep getting extra newlines. Let's see, should be an easy fix.

**Comment by skiadas** [comment]
@whaynes The latest commit should address this, please let me know and close the issue if it does.

**Comment by whaynes** [comment]
Haris,

I ran the new version across my books, and it all looks good.  

Thanks for making this tool, and for your quick response.    ptx-formatter  is really very helpful to me.

Will Haynes
